apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
  name: db-secret

spec:

  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore

  target:
    name: db-secret

  data:
  - secretKey: password

    remoteRef:
      key: db-password
      property: password
